Update Day5-solution1

diff --git a/2024/day05/Day5-solution1 b/2024/day05/Day5-solution1
--- a/2024/day05/Day5-solution1
+++ b/2024/day05/Day5-solution1
@@ -1,1 +1,38 @@
+Create Directories Using Shell Script:
+touch createDirectories.sh
+chmod 700 createDirectories.sh
+vim createDirectories.sh
+i
+SCRIPT:
 
+#!/bin/bash
+
+#variables for arguments
+dir_name=$1
+start_num=$2
+end_num=$3
+
+#check if start_num and end_num are integers
+if ! [[ "$start_num" =~ ^[0-9]+$ || "$end_num" =~ ^[0-9]+$ ]]; then
+                echo "Error:start and end number must be integer."
+                exit 1
+fi
+
+#check if start_num is greater than end_num
+if [ "$start_num" -gt "$end_num" ]; then
+       echo "Error: start number must be less than or equal to end_number"
+       exit 1
+fi 
+
+#loop to create directory
+for ((i=start_num; i<=end_num; i++)); do
+        dir="${dir_name}${i}"
+        mkdir -p "$dir"
+        echo "Created directory: $dir"
+done
+
+SCRIPT END
+
+esc+:+w+q
+
+./createDirectories.sh day 1 90
